# Generated by Django 5.2.5 on 2025-10-05 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reading_lists", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userreadingstats",
            name="user",
        ),
        migrations.DeleteModel(
            name="BookRecommendation",
        ),
        migrations.DeleteModel(
            name="UserReadingStats",
        ),
    ]
