# Generated by Django 5.2.5 on 2025-10-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="feedback_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("bug", "Bug Report"),
                    ("feature", "Feature Request"),
                    ("support", "Support"),
                    ("other", "Other"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
