# Generated by Django 5.2.5 on 2025-08-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_updates"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_verification_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_verification_code_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
