# Generated by Django 5.2.5 on 2025-10-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_emailverificationsession"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("password_hash", models.CharField(max_length=255)),
                ("verification_code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "pending_registrations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="EmailVerificationSession",
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="email_verification_code",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="email_verification_code_sent_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="email_verification_sent_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="email_verification_token",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="favorite_genre",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="reading_goal",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="is_email_verified",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table="user_profiles",
        ),
        migrations.AddIndex(
            model_name="pendingregistration",
            index=models.Index(
                fields=["email", "verification_code"],
                name="pending_reg_email_da98ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pendingregistration",
            index=models.Index(
                fields=["expires_at"], name="pending_reg_expires_f06591_idx"
            ),
        ),
    ]
