# Generated by Django 5.2.5 on 2025-10-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_reviewvote"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReviewLike",
        ),
    ]
