# Generated by Django 5.2.5 on 2025-10-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_delete_reviewlike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
