# Generated by Django 5.2.5 on 2025-10-07 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_make_isbn_nullable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookPurchaseLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seller_name",
                    models.CharField(
                        help_text="Name of the seller (e.g., Amazon, Kitoblar.uz, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Direct link to purchase the book", max_length=500
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this link has been verified by moderators",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="added_purchase_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_links",
                        to="books.book",
                    ),
                ),
            ],
            options={
                "db_table": "book_purchase_links",
                "ordering": ["-is_verified", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["book"], name="book_purcha_book_id_e78da1_idx"
                    ),
                    models.Index(
                        fields=["added_by"], name="book_purcha_added_b_6e9be9_idx"
                    ),
                ],
            },
        ),
    ]
